name: gnome-monthly-x86_64

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 1-12 *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
    - name: Get source
      uses: actions/checkout@v4

    - name: Build system
      run: |
        apt update -y
        apt-get install -y live-build squashfs-tools syslinux-common syslinux-utils xorriso isolinux git curl
        ./build
        mv blade/blade-"$(date -u +%y%m%d)"-amd64.hybrid.iso ~/blade.iso
        cd ../

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: image-x86_64
        path: ~/blade.iso
        if-no-files-found: warn
        retention-days: 90
        compression-level: 0
      
