name: monthly-build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 1-12 *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
    - name: Clone source code
      uses: actions/checkout@v4

    - name: Build ISO
      run: |
        apt update -y
        apt-get install -y live-build squashfs-tools syslinux-common syslinux-utils xorriso isolinux git curl
        git clone https://github.com/Blade-OS/os.git
        cd os/
        ./build
        mv blade/blade/blade-"$(date +%Y%m%d)"-amd64.hybrid.iso blade.iso

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: ISO
        path: os/blade/blade/blade.iso
        if-no-files-found: error
        retention-days: 90
        compression-level: 0
